# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: fix-encoding-pragma
# -   repo: https://github.com/PyCQA/isort
#     rev: ''
#     hooks:
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.32.0'
    hooks:
    - id: yapf
      additional_dependencies: [toml]
#     - id: isort
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
    - id: mypy
      args: [--no-strict-optional, --ignore-missing-imports]
    #   pass_filenames: false
