# -*- coding: utf-8 -*-
"""create tables

Revision ID: f2359984d1a5
Revises:
Create Date: 2023-03-30 10:20:27.477002

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f2359984d1a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'chat_gpt_key', sa.Column('chatkey_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False, comment='用户'),
        sa.Column(
            'content', sa.String(length=256), nullable=False, comment='Key'
        ),
        sa.Column(
            'is_live',
            sa.Boolean(),
            nullable=False,
            comment='是否可用 0表示不可用，1表示可用'
        ), sa.Column('occupy_uid', sa.Integer(), nullable=True, comment='占用者'),
        sa.PrimaryKeyConstraint('chatkey_id')
    )
    op.create_table(
        'conversation', sa.Column('cov_id', sa.Integer(), nullable=False),
        sa.Column(
            'identifier',
            sa.String(length=32),
            nullable=False,
            comment='会话的标识符，在某些情况不适合用id，会用此字段'
        ), sa.Column('user_id', sa.Integer(), nullable=False, comment='用户'),
        sa.Column('create_at', sa.Integer(), nullable=False, comment='创建时间'),
        sa.PrimaryKeyConstraint('cov_id'), sa.UniqueConstraint('identifier')
    )
    op.create_table(
        'user', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'identifier',
            sa.String(length=32),
            nullable=False,
            comment='用户的标识符，在某些情况不适合用id，会用此字段'
        ), sa.Column('email', sa.String(length=64), nullable=False),
        sa.Column('password', sa.String(length=64), nullable=True),
        sa.Column('token', sa.String(length=64), nullable=True),
        sa.Column('create_at', sa.Integer(), nullable=False, comment='创建时间'),
        sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('email'),
        sa.UniqueConstraint('identifier')
    )
    op.create_table(
        'chat_record', sa.Column('chat_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('conversation', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False, comment='聊天内容'),
        sa.Column(
            'role', sa.SMALLINT(), nullable=False, comment='角色，0表示用户，1表示机器人'
        ),
        sa.Column('create_at', sa.Integer(), nullable=False, comment='创建时间'),
        sa.ForeignKeyConstraint(
            ['conversation'],
            ['conversation.cov_id'],
        ), sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ), sa.PrimaryKeyConstraint('chat_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_record')
    op.drop_table('user')
    op.drop_table('conversation')
    op.drop_table('chat_gpt_key')
    # ### end Alembic commands ###
